# Generated by Django 5.1.4 on 2024-12-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalcSimple',
            fields=[
                ('id_calc_simple', models.AutoField(primary_key=True, serialize=False)),
                ('produit', models.CharField(blank=True, max_length=50, null=True)),
                ('nb_achats', models.IntegerField(blank=True, null=True)),
                ('nb_ventes', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ca', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'calc_simple',
            },
        ),
    ]
