# Generated by Django 5.1.4 on 2024-12-16 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('annee', models.DateField(blank=True, null=True)),
                ('code_categorie', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prix_15', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_20', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Coureur',
            fields=[
                ('id_coureur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('sexe', models.CharField(blank=True, max_length=10, null=True)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('taille_tee_shirt', models.CharField(blank=True, max_length=10, null=True)),
                ('prix_club', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('repas_avant_course', models.BooleanField(blank=True, default=False, null=True)),
                ('prix_du_repas_avant_course', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('repas_apres_course', models.BooleanField(blank=True, default=False, null=True)),
                ('prix_du_repas_apres_course', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_coureur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categorie')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course')),
            ],
            options={
                'db_table': 'coureur',
            },
        ),
    ]
