# Generated by Django 5.1.4 on 2024-12-16 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categorie_course_coureur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coureur',
            name='total_coureur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
