# Generated by Django 5.1.4 on 2024-12-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_coureur_total_coureur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='code_categorie',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
